### ISSUE TITLE
Some assets do not import even with the unskinned GMD option

### ISSUE THREAD

**Issue by nyshii** [theturboturnip/yk_gmd_io#25]
I tried importing "acsce2305_sunglass_majima.gmd" (Yakuza 0) with the unskinned GMD option and it gives this error. This might happen with other models but I can't confirm which other ones don't work.

> Python: Traceback (most recent call last):
>   File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\yk_gmd_blender\blender\importer\gmd_importers.py", line 260, in execute
>     gmd_scene = read_abstract_scene_from_filedata_object(gmd_version, False, gmd_contents, error)
>   File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\yk_gmd_blender\yk_gmd\v2\io.py", line 88, in read_abstract_scene_from_filedata_object
>     return GMDAbstractor_YK1(version_props, can_have_skinned_vertices, cast(FileData_YK1, contents), error_reporter).make_abstract_scene()
>   File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\yk_gmd_blender\yk_gmd\v2\converters\yk1\to_abstract.py", line 44, in make_abstract_scene
>     abstract_meshes = self.build_meshes_from_structs(abstract_attributes, abstract_vertex_buffers, abstract_nodes,
>   File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\yk_gmd_blender\yk_gmd\v2\converters\common\to_abstract.py", line 369, in build_meshes_from_structs
>     meshes.append(GMDMesh(
>   File "<string>", line 8, in __init__
>   File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\yk_gmd_blender\yk_gmd\v2\abstract\gmd_mesh.py", line 26, in __post_init__
>     raise TypeError(f"GMDMesh {self} which is not skinned has vertices with bone weights")
> TypeError: GMDMesh <yk_gmd_blender.yk_gmd.v2.abstract.gmd_mesh.GMDMesh object at 0x0000021940A102B0> which is not skinned has vertices with bone weights
> 
> location: <unknown location>:-1

**Comment by bweasty** [comment]
got this issues aswell

**Comment by theturboturnip** [comment]
Same as #27 - projected to be fixed in v0.4
