### ISSUE TITLE
VF5US Stages still not supported after update

### ISSUE THREAD

**Issue by LudoMako** [theturboturnip/yk_gmd_io#27]
Hello, thanks for the tool! I was trying to import in blender(2.92) the aurora stage from virtua fighter 5 ultimate showdown. I tried both skinned and unskinned, some parts of the stage (such as "build") won't import with either options, saying object which is not skinned has vertices with bone weights.

**Comment by adam-antite** [comment]
I also have this same issue with importing stages from Yakuza 7. Most of the stage objects import just fine, but there are big empty spots in the scene where buildings/road objects should be, and I assume these missing areas are where the meshes which failed import with the following error message would be.

`Python: Traceback (most recent call last):
  File "C:\Users\systemuser\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\yk_gmd_blender\blender\importer\gmd_importers.py", line 260, in execute
    gmd_scene = read_abstract_scene_from_filedata_object(gmd_version, False, gmd_contents, error)
  File "C:\Users\adamh\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\yk_gmd_blender\yk_gmd\v2\io.py", line 90, in read_abstract_scene_from_filedata_object
    return GMDAbstractor_Dragon(version_props, can_have_skinned_vertices, cast(FileData_Dragon, contents), error_reporter).make_abstract_scene()
  File "C:\Users\systemuser\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\yk_gmd_blender\yk_gmd\v2\converters\dragon\to_abstract.py", line 47, in make_abstract_scene
    abstract_meshes = self.build_meshes_from_structs(abstract_attributes, abstract_vertex_buffers, abstract_nodes,
  File "C:\Users\systemuser\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\yk_gmd_blender\yk_gmd\v2\converters\common\to_abstract.py", line 369, in build_meshes_from_structs
    meshes.append(GMDMesh(
  File "<string>", line 8, in __init__
  File "C:\Users\systemuser\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\yk_gmd_blender\yk_gmd\v2\abstract\gmd_mesh.py", line 26, in __post_init__
    raise TypeError(f"GMDMesh {self} which is not skinned has vertices with bone weights")`

**Comment by theturboturnip** [comment]
This is projected to be fixed in v0.4, which improves unskinned support.
Branch `v0.4.0-material-refactor` already has fixes for this, but more is still to be done before v0.4 can be released.

**Comment by LudoMako** [comment]
> This is projected to be fixed in v0.4, which improves unskinned support. Branch `v0.4.0-material-refactor` already has fixes for this, but more is still to be done before v0.4 can be released.

I wonder if maybe you could release it as alpha/beta release just to test out if the stages works until it's all merged in 4.0

**Comment by Kasim3157** [comment]
> > This is projected to be fixed in v0.4, which improves unskinned support. Branch `v0.4.0-material-refactor` already has fixes for this, but more is still to be done before v0.4 can be released.
> 
> I wonder if maybe you could release it as alpha/beta release just to test out if the stages works until it's all merged in 4.0

You can download v0.4.0-material-refactor in here
https://github.com/theturboturnip/yk_gmd_io/tree/v0.4.0-material-refactor

put "yk_gmd_blender folder" in to Blender
but blender will show error message
`  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\yk_gmd_blender\yk_gmd\v2\converters\common\to_abstract.py", line 93, in GMDAbstractor_Common
    -> List[GMDVertexBuffer_Generic]:
NameError: name 'GMDVertexBuffer_Generic' is not defined`

Open yk_gmd\v2\converters\common\to_abstract.py
in line 15
`from yk_gmd_blender.yk_gmd.v2.abstract.gmd_shader import GMDShader, GMDVertexBufferLayout`
add "GMDVertexBuffer_Generic" in it, let right call from Shader
`from yk_gmd_blender.yk_gmd.v2.abstract.gmd_shader import GMDShader, GMDVertexBuffer_Generic, GMDVertexBufferLayout`

it work on me, can success import gmd mesh in Blender

**Comment by LudoMako** [comment]
Thank you SO much, can't wait to try this method out!
