### ISSUE TITLE
Model not exporting!

### ISSUE THREAD

**Issue by riskyMA** [theturboturnip/yk_gmd_io#67]
whenever I try exporting I get a prompt saying basically saying
![image_2023-08-14_135052052](https://github.com/theturboturnip/yk_gmd_io/assets/142230437/a9aab197-1ff5-4fd1-8bd6-ff6d7177eb1d)

**Comment by riskyMA** [comment]
I've been trying to export lau ka long

**Comment by NaufalFajri** [comment]
if you using blender 2.92 use this version
https://github.com/theturboturnip/yk_gmd_io/releases/tag/v0.3.2p1
