### ISSUE TITLE
Error when exporting

### ISSUE THREAD

**Issue by pjstarr12** [theturboturnip/yk_gmd_io#69]
Blender version: 2.93.4
Error:
![image](https://github.com/theturboturnip/yk_gmd_io/assets/85199112/074cbd6f-5606-429c-b418-95a617059eb6)
No clue why, I've done everything I can. The yakuza modding community wont help.

**Comment by theturboturnip** [comment]
The addon requires blender version 3.2.0 at minimum. Try an older version?
