### ISSUE TITLE
Weird textures

### ISSUE THREAD

**Issue by KamnTry** [theturboturnip/yk_gmd_io#70]
![image](https://github.com/theturboturnip/yk_gmd_io/assets/147007345/906ea761-fe35-45a1-a41b-769d3ede6604)

Sorry if this is a dumb question, but how do I fix these purple textures? I'm very new to Blender and not too great with code.

**Comment by nyshii** [comment]
open common.par in adv folder and relink images in file > external data to its unpacked folder.

**Comment by KamnTry** [comment]
> open common.par in adv folder and relink images in file > external data to its unpacked folder.

Thank you so much!! You're a lifesaver!
